# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8914dad9f975dd0bf2ae14b2576a8c8ad957598be15281a89b345570bc5008c453d9d6cf5642fb043be8f95b36c3b17c93a57976630f1361757f325432640b24

test:
  secret_key_base: 91d43d99bc6e0bb2247c87e1f5df4306185818c3e074d56a0f1754c713be7df241c488ba88ea41fe3c389e7ddf87f003c72daf58eb90f3dcb3210454ff5b149c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
